"""One-off correction: restate Employer ESI / Employer PF on submitted Salary Slips.

Context
-------
The June 2026 structures computed the employer-side statistical rows wrongly:
Employer ESI was pro-rated twice on slips with absent days (its formula used the
already-earned Basic and the row pro-rated it again), and Employer PF was a flat
12% x 15,000 pro-rated by payment days instead of 12% x min(earned Basic, ceiling).
Those rows only drive the employer provision GL (Dr expense / Cr payable) — they
are statistical, so gross and net pay never included them.

This script recomputes ONLY those two rows from each slip's own earned Basic + DA:

    Employer ESI = ceil(esi_employer_rate x earned wage)        (rounded up, per ESIC)
    Employer PF  = round(pf_employer_rate x min(earned wage, pf_ceiling))

It never touches employee deductions, gross or net pay (salary was already paid on
them), so Payroll Payable is unchanged. Amounts on submitted child rows are not
allow_on_submit, hence a direct data fix (frappe.db.set_value), recorded as a
Comment on each slip. GL is then regenerated by ERPNext's Repost Accounting Ledger
(Salary Slip is enabled for it by the allow_salary_slip_repost patch), which
reverses the old rows and posts new ones — nothing is cancelled or deleted.

Usage (ALWAYS dry-run first)
----------------------------
    # 1. Dry run — lists every change, mutates nothing:
    bench --site hrms.rbcolour.com execute \
        indian_hrms_compliance.scripts.restate_employer_statutory.run \
        --kwargs "{'from_date': '2026-07-01', 'to_date': '2026-08-31', 'pf_ceiling': 15000}"

    # 2. Apply and queue the GL repost:
    bench --site hrms.rbcolour.com execute \
        indian_hrms_compliance.scripts.restate_employer_statutory.run \
        --kwargs "{'from_date': '2026-07-01', 'to_date': '2026-08-31', 'pf_ceiling': 15000, 'apply': 1, 'repost': 1}"

Optional kwargs
---------------
    company      limit to one Company (default: all)
    slips        list of Salary Slip names (overrides the date filter)
    pf_ceiling   PF wage ceiling in force for those months (default: HR Settings)
    repost       with apply, create Repost Accounting Ledger docs (50 slips each,
                 per company) for the changed slips; they start automatically

Idempotent: rows already at the correct amount are skipped.
"""

import math

import frappe
from frappe.utils import flt

from indian_hrms_compliance.hr.doctype.statutory_component_mapping.statutory_component_mapping import (
	get_mapping_for_company,
)
from indian_hrms_compliance.overrides.salary_structure_validator import _is_pf_wage_row

REPOST_BATCH = 50  # ERPNext's MAX_VOUCHERS_PER_REPOST


def run(apply=0, repost=0, company=None, from_date=None, to_date=None, slips=None, pf_ceiling=None):
	apply, repost = int(apply), int(repost)
	settings = frappe.get_single("HR Settings")
	pf_ceiling = flt(pf_ceiling) or flt(settings.pf_wage_ceiling) or 15000
	pf_rate = flt(settings.pf_employer_rate_pct or 12) / 100
	esi_rate = flt(settings.esi_employer_rate_pct or 3.25) / 100

	names = _slips_in_scope(company, from_date, to_date, slips)
	print(
		f"{'APPLY' if apply else 'DRY RUN'}: {len(names)} submitted slip(s); PF ceiling {pf_ceiling:,.0f}, "
		f"employer PF {pf_rate:.2%}, employer ESI {esi_rate:.2%}"
	)

	changed = {}
	for name in names:
		slip = frappe.get_doc("Salary Slip", name)
		changes = _restate(slip, pf_ceiling, pf_rate, esi_rate)
		if not changes:
			continue
		changed[name] = slip.company
		for row, old, new, why in changes:
			print(f"  {name:32} {row.salary_component:26} {old:>10,.2f} -> {new:>10,.2f}  ({why})")
			if apply:
				frappe.db.set_value(
					"Salary Detail", row.name, {"amount": new, "default_amount": new}, update_modified=False
				)
		if apply:
			slip.add_comment(
				"Comment",
				"Employer statutory rows restated (employee deductions, gross and net unchanged):<br>"
				+ "<br>".join(f"{r.salary_component}: {o:,.2f} → {n:,.2f} ({w})" for r, o, n, w in changes),
			)

	print(f"{len(changed)} slip(s) {'restated' if apply else 'would be restated'}.")
	if apply:
		frappe.db.commit()
		if repost and changed:
			for docname in _queue_repost(changed):
				print(f"  Repost Accounting Ledger {docname} submitted (runs in background)")
	return {"slips": list(changed)}


def _slips_in_scope(company, from_date, to_date, slips):
	if slips:
		names = frappe.parse_json(slips) if isinstance(slips, str) else list(slips)
		return frappe.get_all("Salary Slip", filters={"name": ("in", names), "docstatus": 1}, pluck="name")
	filters = {"docstatus": 1}
	if company:
		filters["company"] = company
	if from_date:
		filters["start_date"] = (">=", from_date)
	if to_date:
		filters["end_date"] = ("<=", to_date)
	return frappe.get_all("Salary Slip", filters=filters, order_by="start_date, name", pluck="name")


def _restate(slip, pf_ceiling, pf_rate, esi_rate):
	"""[(row, old, new, reason)] for the employer rows that are off by a paisa or more."""
	mapping = get_mapping_for_company(slip.company)
	wage = sum(
		flt(r.amount)
		for r in slip.earnings
		if _is_pf_wage_row(r, mapping) and not r.statistical_component and not r.additional_salary
	)
	esi_component = (mapping and mapping.esi_employer_component) or "Employer ESI"
	pf_component = (mapping and mapping.pf_employer_component) or "Employer Provident Fund"

	changes = []
	for row in slip.earnings:
		# Only statistical, out-of-total rows: never anything that feeds gross or net.
		if not (row.statistical_component and row.do_not_include_in_total) or row.additional_salary:
			continue
		if row.salary_component == esi_component:
			new = math.ceil(round(esi_rate * wage, 6))
			why = f"{esi_rate:.2%} of earned wage {wage:,.2f}, rounded up"
		elif row.salary_component == pf_component:
			new = round(pf_rate * min(wage, pf_ceiling))
			why = f"{pf_rate:.0%} of min(earned wage {wage:,.2f}, {pf_ceiling:,.0f})"
		else:
			continue
		if abs(flt(row.amount) - new) >= 0.01:
			changes.append((row, flt(row.amount), flt(new), why))
	return changes


def _queue_repost(changed):
	by_company = {}
	for name, company in changed.items():
		by_company.setdefault(company, []).append(name)
	created = []
	for company, names in by_company.items():
		for i in range(0, len(names), REPOST_BATCH):
			ral = frappe.get_doc(
				{
					"doctype": "Repost Accounting Ledger",
					"company": company,
					"delete_cancelled_entries": 0,
					"vouchers": [
						{"voucher_type": "Salary Slip", "voucher_no": n} for n in names[i : i + REPOST_BATCH]
					],
				}
			)
			ral.insert(ignore_permissions=True)
			ral.submit()
			created.append(ral.name)
	frappe.db.commit()
	return created
